name: Android CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint:
    name: Run ktlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant Gradle permission
      run: chmod +x ./gradlew

    - name: Run ktlint check
      run: ./gradlew ktlintCheck

    - name: Upload ktlint report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ktlint-report
        path: app/build/reports/ktlint/

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint  # Run only if lint passed
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant Gradle permission
      run: chmod +x ./gradlew

    - name: Build and run tests
      run: ./gradlew build test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: app/build/reports/tests/

    - name: Print test summary
      if: always()
      run: |
        find app/build/reports/tests -name "*.xml" -exec grep -l "<failure" {} \; | while read file; do
          echo "Test failures in $file:"
          grep "<testcase" "$file" | grep -B1 "<failure" || echo "No test failures"
        done